### ISSUE TITLE
access the arguments in an after callback

### ISSUE THREAD

**Issue by subtleGradient** [ryanflorence/publisher.js#1]
the registration of an `after` callback is currently `function(returnValue, object)`, ideally it should be something like `function(returnValue, object, arg1, arg2, …)` so that you can access the arguments without having to also create a before and cache them.

**Comment by ryanflorence** [comment]
This keeps coming up.  Will definitely add.

**Comment by ryanflorence** [comment]
Added, it locally, updating docs.
