### ISSUE TITLE
Errors as AMD module with RequireJS Optimization

### ISSUE THREAD

**Issue by mjtognetti** [ryanflorence/publisher.js#5]
When run as an AMD module and optimized by @jrburke 's RequireJS, Publisher fails to be defined as a module. Instead an empty `define('publisher', function(){})` is produced, breaking any code Publisher-dependent code.

Quoting @jrburke from https://github.com/ded/morpheus/issues/19 , in which an identical problem and its solution are discussed:

> The issue is that the requirejs optimizer uses an AST to find define() calls that look like AMD define calls.  Since define(definition) is a bit too generic it skips it and puts in an empty module for the 'morpheus' name.
> 
> Two possible easy fixes:
> 
> 1) Use a function literal:
> 
> `if (typeof define == 'function') define(function(){return definition()})`
> 
> 2) Or just pass name to the function:
> 
> `if (typeof define == 'function') define(name, definition)`

**Comment by ryanflorence** [comment]
closed by PR #6
